### ISSUE TITLE
Add support of CSV files

### ISSUE THREAD

**Issue by dualbios** [dualbios/FileBaseContext#19]

**Comment by dualbios** [comment]
draw of implementation https://github.com/dualbios/FileBaseContext/tree/csv-serializer

**Comment by dualbios** [comment]
need to extract IRowDataSerializerFactory first.

**Comment by daveidmx** [comment]
I took a look at your branch. This is your repo, obviously, so my opinions have little weight, but a couple ideas:
* Don't forget to escape cell values. (If the string value contains `"` or `,`, wrap it in quotes and double any internal quotes; e.g `"Hello, World"` --> `"""Hello, World"""`.) Add some tests to cover difficult cases.
* Add handling and test cases for round-tripping null-versus-empty. I don't think there's a standard for how to handle this in CSV since CSV doesn't understand nulls, but a couple ideas come to mind. Unfortunately, none of these will safely round-trip through Excel, but that could be considered an unsupported case.
    a) You could encode null as "no content" (`,,`) and empty string as empty quotes (`,"",`)
    b) You could encode null as an unquoted special string like `NULL`, the Excel null `=#NULL!`, or `FileBaseContext#NULL`, and differentiate data strings of those values by quoting them. Unfortunately, loading, saving, and reloading any of those through Excel CSV will result in losing the quote differentiation and `=` prefix. (But again, that could be considered unsupported.)
* If that `Console.WriteLine(e);` is intended to stay after initial implementation, consider taking an `ILogger`/`ILogger<T>` constructor arg and write to that instead.
* Re adding `DbContextTestClassBase.ReadFileContext(string)` and calling it as `ReadFileContext(GetDatabaseFullFileName(nameof(User) + ".csv"));` (etc.): There is another helper method `ReadDatabaseFileText(string)` that does the database name stuff so you can just do `ReadDatabaseFileText(nameof(User) + ".csv")`. (Feel free to rename it if it would improve discoverability.)

**Comment by dualbios** [comment]
@daveidmx 
 thanks a lot for the comments!
I decided to split the implementation into 2 steps. so I can parallelise the efforts.
first, I want to implement IRowDataSerializerFactory.

please look at the PR https://github.com/dualbios/FileBaseContext/pull/21.
I don't know why I can't add you as a reviewer.
